### ISSUE TITLE
Handle 5.7 Package.resolved format

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/ReleaseNotes#9]
Swift 5.7 comes with a new `Package.resolved` format that we're not handling yet:

```json
{
  ...
  "version" : 2
}
```

This leads to a blank PR using @MarcoEidinger 's swift-package-dependencies-check workflow.

![CleanShot 2022-10-10 at 09 31 51@2x](https://user-images.githubusercontent.com/65520/194818580-fea6a28e-a5b2-465f-b936-d29018d5cbb1.png)

(Side note: it's probably better in this case for the action not to fail entirely but perhaps it could inject an explanation into the PR text in case `swift-release-notes` fails.)

**Comment by finestructure** [comment]
Released as 0.0.7

cc @MarcoEidinger

**Comment by MarcoEidinger** [comment]
Used in swift-package-dependencies-check workflow with latest `2.3.3` version (to which `v2` points to)

cc @finestructure
